### ISSUE TITLE
Type safety around Required/nullable values

### ISSUE THREAD

**Issue by charlesroddie** [ahhsoftware/SQLPlusSampleApp#1]
Great library. Very well documented and motivated. I'm investigating it as an alternative to FSharp.Data.SqlClient which does something similar (generates .Net types from SQL). SQLPlus just has more manual control over when types get built which we would prefer. One thing that FSharp.Data.SqlClient does well - and this library could do - is type safety. Since FSharp.Data.SqlClient is F# it has access to a long-running tradition of F# option types. But C# with NRTs is now able to get a similar level of safety in this context.

I tried an SQLPlus build with a simple SQL function which illustrates this.

### Required inputs and Input constructors

```sql
CREATE FUNCTION UsersInClass(
    --+Required
    @classId INT
)
```

This generates a `UsersInClassInput`:

```csharp
public class UsersInClassInput : ValidInput, IUsersInClassInput
{
    public int? classId { set; get; }
}
```

Problem:
- classId is `Nullable<int>` despite having a `--+Required` annotation.
- There is no information given to users that classId should be set.

Suggestions:
- Inputs are treated as `Required` unless marked as optional. Since I would expect it's unusual to have intentionally optional inputs to SQL functions and procedures.
- There is a constructor in which required properties are non-nullable and non-required properties are nullable:

```csharp
public UsersInClassInput(int classId) {...}
```

### Nullable Reference Types

```csharp
public partial class UsersInClassResult
{
    public int Id { set; get; }
    public Guid ADUserId { set; get; }
    public string LastName { set; get; } // This is OK
    public string Email { set; get; } // This should be string?
    public DateTime? LastLoggedIn { set; get; }
}
```
The Result type does better than the Input type in terms of indicating nullability, in that struct types are correctly marked as nullable or non-nullable. However reference types (`string` here) have no indication of nullability, presumably because this library predates NRTs.

Suggestion:
- Annotating optional properties as nullable reference types would be a major upgrade.

**Comment by ahhsoftware** [comment]
From a database perspective every parameter is nullable, so the nullability on properties in the generated input object is accurate.

Marking a parameter with the required tag, means that a value must be set in order for the input object to pass validation.

What is missing from your example is the data annotations escalated from the SQL.

`
public class UsersInClassInput : ValidInput, IUsersInClassInput
{
        [Required]
        public int? classId { set; get; }
}
